---
name: "set-dino2"
channels:
  - rapidsai
  - pytorch
  - conda-forge
  - nvidia
  - nodefaults
dependencies:
  - python=3.10
  - ipykernel
  - pytorch=2.0.0
  - torchvision=0.15.2
  - pytorch-cuda=11.8
  - cuml=24.04
  - cupy=13.1.0
  - opencv=4.8.1
  - pip
  - pip:
      - pytorch-lightning==2.2.4
      - pandas==1.5.3
      - zarr==2.18.0
      - pyarrow==12.*
      - scikit-learn==1.4.2
      - numpy==1.24.0
      - scikit-image==0.23.2
      - opencv-contrib-python-headless==4.9.0.80
      - wandb==0.17.0
      - timm==0.9.16
      - lmdb==1.4.0
      - fastparquet==2024.2.0
      - matplotlib==3.9.0
      - jupyterlab